name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0

    - name: Install dependencies
      run: |
          cd src
          npm ci  # Considerar trocar para npm ci se houver package-lock.json

    - name: Build React app
      run: |
          cd src
          npm run build
    
    - name: Authenticate to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
        
    - name: Build the Docker image
      run: docker build -f ./src/Dockerfile -t matheusduarte21/minikube:${{ github.sha }} ./src

    - name: Push the Docker image
      run: docker push matheusduarte21/minikube:${{ github.sha }}

