name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0

    - name: Install dependencies
      run: |
          npm install

    - name: Build React app
      run: |
          npm run build
    
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
        
    - name: Build the Docker image
      run: docker build -f ./Dockerfile -t matheusduarte21/minikube:v1 .

    - name: Push the Docker image
      run: docker push matheusduarte21/minikube:v1
      
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - uses: actions/checkout@v4.2.0

      - name: definindo o context
        uses: Azure/k8s-set-context@v3.0
        with:
            method: kubeconfig
            kubeconfig: ${{ secrets.K8S_CONFIG }}
  
