name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0
    
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
        
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./src --file ./src/Dockerfile --tag my-image-name:$(date +%s)


      
