
name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0
    
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
        
    - name: Build the Docker image
      run: docker build -f ./src/Dockerfile -t matheusduarte21/minikube:${{github.run_number}} ./src

    - name: Push the Docker image
      run: docker push matheusduarte21/minikube:latest

