name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0

    - name: List files in src
      run: |
          cd src
          ls -la

    - name: Install dependencies
      run: |
          cd src
          npm install

    - name: Check for react-scripts
      run: |
          cd src
          ls -la node_modules/react-scripts

    - name: Build React app
      run: |
          cd src
          npx react-scripts build
    
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
        
    - name: Build the Docker image
      run: docker build -f ./src/Dockerfile -t matheusduarte21/minikube:v1 ./src

    - name: Push the Docker image
      run: docker push matheusduarte21/minikube:v1
